import 'dart:io';

import 'package:dio/dio.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:ntfyd/core/error/exception_mapper.dart';
import 'package:ntfyd/core/error/failures.dart';

// Helper: builds a DioException that looks like a real HTTP error response
DioException _makeDioException(int statusCode) {
  return DioException(
    requestOptions: RequestOptions(path: '/test'),
    response: Response(
      requestOptions: RequestOptions(path: '/test'),
      statusCode: statusCode,
    ),
    type: DioExceptionType.badResponse,
  );
}

// Helper: builds a DioException that looks like a dropped connection
DioException _makeDioConnectionError() {
  return DioException(
    requestOptions: RequestOptions(path: '/test'),
    type: DioExceptionType.connectionError,
    message: 'Connection refused',
  );
}

void main() {
  group('ExceptionMapper => DioException status codes', () {
    test('maps 401 : AuthFailure with statusCode 401', () {
      // ARRANGE: a DioException with a 401 response
      final exception = _makeDioException(401);

      final result = ExceptionMapper.map(exception);

      expect(result, const Failure.auth(statusCode: 401));
    });

    test('maps 403 → AuthFailure with statusCode 403', () {
      final result = ExceptionMapper.map(_makeDioException(403));
      expect(result, const Failure.auth(statusCode: 403));
    });

    test('maps 404 → NotFoundFailure', () {
      final result = ExceptionMapper.map(_makeDioException(404));
      expect(result, const Failure.notFound());
    });

    test('maps 429 → RateLimitFailure', () {
      final result = ExceptionMapper.map(_makeDioException(429));
      expect(result, const Failure.rateLimit());
    });

    test('maps 500 → ServerFailure with statusCode 500', () {
      final result = ExceptionMapper.map(_makeDioException(500));

      // We check the type first, then cast to read the field.
      // We use isA<ServerFailure>() because the message field comes
      // from DioException.message which may vary — we only care that
      // the status code is preserved.
      expect(result, isA<ServerFailure>());
      expect((result as ServerFailure).statusCode, 500);
    });

    test('maps DioException connectionError → NetworkFailure', () {
      final result = ExceptionMapper.map(_makeDioConnectionError());
      expect(result, isA<NetworkFailure>());
    });
  });

  group('ExceptionMapper — non-Dio exceptions', () {
    test('maps SocketException → NetworkFailure', () {
      // SocketException is a Dart IO exception for dropped connections
      final result = ExceptionMapper.map(
        const SocketException('Connection refused'),
      );
      expect(result, isA<NetworkFailure>());
    });

    test('maps FormatException → UnknownFailure', () {
      // FormatException happens when JSON parsing fails
      final result = ExceptionMapper.map(const FormatException('bad json'));
      expect(result, isA<UnknownFailure>());
    });
  });

  group('Failure — Freezed equality', () {
    test('two NetworkFailures with identical fields are equal', () {
      const a = Failure.network(message: 'err', statusCode: 503);
      const b = Failure.network(message: 'err', statusCode: 503);

      // Freezed generates == based on field values, not object identity
      expect(a, equals(b));
    });

    test('two NetworkFailures with different fields are NOT equal', () {
      const a = Failure.network(message: 'err', statusCode: 503);
      const b = Failure.network(message: 'err', statusCode: 500);
      expect(a, isNot(equals(b)));
    });

    test('copyWith updates only the specified field', () {
      const original = Failure.network(message: 'err', statusCode: 503);

      // copyWith is generated by Freezed — it returns a NEW instance
      // with only the fields you specified changed
      final copy = (original as NetworkFailure).copyWith(statusCode: 500);

      expect(copy.statusCode, 500);
      expect(copy.message, 'err');
      expect(copy, isNot(same(original)));
    });
  });

  group('Failure — exhaustive when()', () {
    test('when() routes each of the 9 subtypes to the correct branch', () {
      // One instance of every subtype
      final failures = <Failure>[
        const Failure.network(message: 'n'),
        const Failure.auth(statusCode: 401),
        const Failure.notFound(),
        const Failure.rateLimit(),
        const Failure.server(statusCode: 500, message: 's'),
        const Failure.cache(message: 'c'),
        const Failure.validation(field: 'f', message: 'm'),
        const Failure.biometric(reason: 'b'),
        const Failure.unknown(message: 'u'),
      ];

      // Expected label for each, in the same order as the list above
      final expected = [
        'network',
        'auth',
        'notFound',
        'rateLimit',
        'server',
        'cache',
        'validation',
        'biometric',
        'unknown',
      ];

      for (var i = 0; i < failures.length; i++) {
        final label = failures[i].when(
          network: (_, _) => 'network',
          auth: (_) => 'auth',
          notFound: () => 'notFound',
          rateLimit: (_) => 'rateLimit',
          server: (_, _) => 'server',
          cache: (_) => 'cache',
          validation: (_, _) => 'validation',
          biometric: (_) => 'biometric',
          unknown: (_) => 'unknown',
        );
        expect(label, expected[i]);
      }
    });
  });
}
